#!/usr/bin/env bash
# script that will display information about the subdomains
# Output: The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]

dislay_dns_info() {
	script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
	dislay_dns_info "$1" "www"
	dislay_dns_info "$1" "lb-01"
	dislay_dns_info "$1" "web-01"
	dislay_dns_info "$1" "web-02"
elif [ "$#" == 2 ]
then
	dislay_dns_info "$1" "$2"
fi
