#!/usr/bin/env bash
# Installs and setup haproxy

sudo apt-get update
sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
# confiuration of the default haproxy
cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend Randomallstudio.tech
        # Sets a custom client
        timeout client 30000
        bind 0:80
        default_backend Randomallstudio.tech_backend

backend Randomallstudio.tech_backend
        timeout connect 3000
        timeout server 30000
        balance roundrobin
        server 207676-web-01 52.23.245.178:80 check
        server 207676-web-02 52.23.222.215:80 check
EOT

sudo service haproxy restart